package com.eumenides.entity;

public class CollectUserProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_user_project.collectId
     *
     * @mbggenerated
     */
    private Integer collectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_user_project.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_user_project.projectId
     *
     * @mbggenerated
     */
    private Integer projectid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_user_project.collectId
     *
     * @return the value of collect_user_project.collectId
     *
     * @mbggenerated
     */
    public Integer getCollectid() {
        return collectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_user_project.collectId
     *
     * @param collectid the value for collect_user_project.collectId
     *
     * @mbggenerated
     */
    public void setCollectid(Integer collectid) {
        this.collectid = collectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_user_project.userId
     *
     * @return the value of collect_user_project.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_user_project.userId
     *
     * @param userid the value for collect_user_project.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_user_project.projectId
     *
     * @return the value of collect_user_project.projectId
     *
     * @mbggenerated
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_user_project.projectId
     *
     * @param projectid the value for collect_user_project.projectId
     *
     * @mbggenerated
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }
}