package com.eumenides.entity;

public class CollectUserRecruit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_user_recruit.collectId
     *
     * @mbggenerated
     */
    private Integer collectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_user_recruit.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_user_recruit.recruitId
     *
     * @mbggenerated
     */
    private Integer recruitid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_user_recruit.collectId
     *
     * @return the value of collect_user_recruit.collectId
     *
     * @mbggenerated
     */
    public Integer getCollectid() {
        return collectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_user_recruit.collectId
     *
     * @param collectid the value for collect_user_recruit.collectId
     *
     * @mbggenerated
     */
    public void setCollectid(Integer collectid) {
        this.collectid = collectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_user_recruit.userId
     *
     * @return the value of collect_user_recruit.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_user_recruit.userId
     *
     * @param userid the value for collect_user_recruit.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_user_recruit.recruitId
     *
     * @return the value of collect_user_recruit.recruitId
     *
     * @mbggenerated
     */
    public Integer getRecruitid() {
        return recruitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_user_recruit.recruitId
     *
     * @param recruitid the value for collect_user_recruit.recruitId
     *
     * @mbggenerated
     */
    public void setRecruitid(Integer recruitid) {
        this.recruitid = recruitid;
    }
}