package com.eumenides.entity;

import java.math.BigDecimal;
import java.util.Date;

public class CoRecruit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_recruit.recruitId
     *
     * @mbggenerated
     */
    private Integer recruitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_recruit.companyId
     *
     * @mbggenerated
     */
    private Integer companyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_recruit.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_recruit.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_recruit.salary
     *
     * @mbggenerated
     */
    private BigDecimal salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_recruit.education
     *
     * @mbggenerated
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_recruit.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_recruit.finalTime
     *
     * @mbggenerated
     */
    private Date finaltime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_recruit.label
     *
     * @mbggenerated
     */
    private String label;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_recruit.recruitId
     *
     * @return the value of co_recruit.recruitId
     *
     * @mbggenerated
     */
    public Integer getRecruitid() {
        return recruitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_recruit.recruitId
     *
     * @param recruitid the value for co_recruit.recruitId
     *
     * @mbggenerated
     */
    public void setRecruitid(Integer recruitid) {
        this.recruitid = recruitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_recruit.companyId
     *
     * @return the value of co_recruit.companyId
     *
     * @mbggenerated
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_recruit.companyId
     *
     * @param companyid the value for co_recruit.companyId
     *
     * @mbggenerated
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_recruit.title
     *
     * @return the value of co_recruit.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_recruit.title
     *
     * @param title the value for co_recruit.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_recruit.address
     *
     * @return the value of co_recruit.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_recruit.address
     *
     * @param address the value for co_recruit.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_recruit.salary
     *
     * @return the value of co_recruit.salary
     *
     * @mbggenerated
     */
    public BigDecimal getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_recruit.salary
     *
     * @param salary the value for co_recruit.salary
     *
     * @mbggenerated
     */
    public void setSalary(BigDecimal salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_recruit.education
     *
     * @return the value of co_recruit.education
     *
     * @mbggenerated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_recruit.education
     *
     * @param education the value for co_recruit.education
     *
     * @mbggenerated
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_recruit.description
     *
     * @return the value of co_recruit.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_recruit.description
     *
     * @param description the value for co_recruit.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_recruit.finalTime
     *
     * @return the value of co_recruit.finalTime
     *
     * @mbggenerated
     */
    public Date getFinaltime() {
        return finaltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_recruit.finalTime
     *
     * @param finaltime the value for co_recruit.finalTime
     *
     * @mbggenerated
     */
    public void setFinaltime(Date finaltime) {
        this.finaltime = finaltime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_recruit.label
     *
     * @return the value of co_recruit.label
     *
     * @mbggenerated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_recruit.label
     *
     * @param label the value for co_recruit.label
     *
     * @mbggenerated
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }
}