package com.eumenides.entity;

public class Group {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.groupId
     *
     * @mbggenerated
     */
    private Integer groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column group.leaderId
     *
     * @mbggenerated
     */
    private Integer leaderid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.groupId
     *
     * @return the value of group.groupId
     *
     * @mbggenerated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.groupId
     *
     * @param groupid the value for group.groupId
     *
     * @mbggenerated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.name
     *
     * @return the value of group.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.name
     *
     * @param name the value for group.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column group.leaderId
     *
     * @return the value of group.leaderId
     *
     * @mbggenerated
     */
    public Integer getLeaderid() {
        return leaderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column group.leaderId
     *
     * @param leaderid the value for group.leaderId
     *
     * @mbggenerated
     */
    public void setLeaderid(Integer leaderid) {
        this.leaderid = leaderid;
    }
}