package com.eumenides.entity;

public class Groupinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupinfo.recordId
     *
     * @mbggenerated
     */
    private Integer recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupinfo.groupId
     *
     * @mbggenerated
     */
    private Integer groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupinfo.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groupinfo.captain
     *
     * @mbggenerated
     */
    private Integer captain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupinfo.recordId
     *
     * @return the value of groupinfo.recordId
     *
     * @mbggenerated
     */
    public Integer getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupinfo.recordId
     *
     * @param recordid the value for groupinfo.recordId
     *
     * @mbggenerated
     */
    public void setRecordid(Integer recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupinfo.groupId
     *
     * @return the value of groupinfo.groupId
     *
     * @mbggenerated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupinfo.groupId
     *
     * @param groupid the value for groupinfo.groupId
     *
     * @mbggenerated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupinfo.userId
     *
     * @return the value of groupinfo.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupinfo.userId
     *
     * @param userid the value for groupinfo.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groupinfo.captain
     *
     * @return the value of groupinfo.captain
     *
     * @mbggenerated
     */
    public Integer getCaptain() {
        return captain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groupinfo.captain
     *
     * @param captain the value for groupinfo.captain
     *
     * @mbggenerated
     */
    public void setCaptain(Integer captain) {
        this.captain = captain;
    }
}