package com.eumenides.entity;

public class NoticeParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_param.param_id
     *
     * @mbggenerated
     */
    private Integer paramId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_param.notice_id
     *
     * @mbggenerated
     */
    private Integer noticeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_param.param_key
     *
     * @mbggenerated
     */
    private String paramKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_param.param_value
     *
     * @mbggenerated
     */
    private String paramValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_param.param_id
     *
     * @return the value of notice_param.param_id
     *
     * @mbggenerated
     */
    public Integer getParamId() {
        return paramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_param.param_id
     *
     * @param paramId the value for notice_param.param_id
     *
     * @mbggenerated
     */
    public void setParamId(Integer paramId) {
        this.paramId = paramId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_param.notice_id
     *
     * @return the value of notice_param.notice_id
     *
     * @mbggenerated
     */
    public Integer getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_param.notice_id
     *
     * @param noticeId the value for notice_param.notice_id
     *
     * @mbggenerated
     */
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_param.param_key
     *
     * @return the value of notice_param.param_key
     *
     * @mbggenerated
     */
    public String getParamKey() {
        return paramKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_param.param_key
     *
     * @param paramKey the value for notice_param.param_key
     *
     * @mbggenerated
     */
    public void setParamKey(String paramKey) {
        this.paramKey = paramKey == null ? null : paramKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_param.param_value
     *
     * @return the value of notice_param.param_value
     *
     * @mbggenerated
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_param.param_value
     *
     * @param paramValue the value for notice_param.param_value
     *
     * @mbggenerated
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue == null ? null : paramValue.trim();
    }
}