package com.eumenides.entity;

import java.util.Date;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.projectId
     *
     * @mbggenerated
     */
    private Integer projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.companyId
     *
     * @mbggenerated
     */
    private Integer companyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.reward
     *
     * @mbggenerated
     */
    private Long reward;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.relaseTime
     *
     * @mbggenerated
     */
    private Date relasetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.endTime
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.finishTime
     *
     * @mbggenerated
     */
    private Date finishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.label
     *
     * @mbggenerated
     */
    private String label;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.companyName
     *
     * @mbggenerated
     */
    private String companyname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.projectId
     *
     * @return the value of project.projectId
     *
     * @mbggenerated
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.projectId
     *
     * @param projectid the value for project.projectId
     *
     * @mbggenerated
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.title
     *
     * @return the value of project.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.title
     *
     * @param title the value for project.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.companyId
     *
     * @return the value of project.companyId
     *
     * @mbggenerated
     */
    public Integer getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.companyId
     *
     * @param companyid the value for project.companyId
     *
     * @mbggenerated
     */
    public void setCompanyid(Integer companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.description
     *
     * @return the value of project.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.description
     *
     * @param description the value for project.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.reward
     *
     * @return the value of project.reward
     *
     * @mbggenerated
     */
    public Long getReward() {
        return reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.reward
     *
     * @param reward the value for project.reward
     *
     * @mbggenerated
     */
    public void setReward(Long reward) {
        this.reward = reward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.relaseTime
     *
     * @return the value of project.relaseTime
     *
     * @mbggenerated
     */
    public Date getRelasetime() {
        return relasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.relaseTime
     *
     * @param relasetime the value for project.relaseTime
     *
     * @mbggenerated
     */
    public void setRelasetime(Date relasetime) {
        this.relasetime = relasetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.endTime
     *
     * @return the value of project.endTime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.endTime
     *
     * @param endtime the value for project.endTime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.finishTime
     *
     * @return the value of project.finishTime
     *
     * @mbggenerated
     */
    public Date getFinishtime() {
        return finishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.finishTime
     *
     * @param finishtime the value for project.finishTime
     *
     * @mbggenerated
     */
    public void setFinishtime(Date finishtime) {
        this.finishtime = finishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.label
     *
     * @return the value of project.label
     *
     * @mbggenerated
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.label
     *
     * @param label the value for project.label
     *
     * @mbggenerated
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.companyName
     *
     * @return the value of project.companyName
     *
     * @mbggenerated
     */
    public String getCompanyname() {
        return companyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.companyName
     *
     * @param companyname the value for project.companyName
     *
     * @mbggenerated
     */
    public void setCompanyname(String companyname) {
        this.companyname = companyname == null ? null : companyname.trim();
    }
}