package com.eumenides.entity;

public class ProjectStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_status.projectId
     *
     * @mbggenerated
     */
    private Integer projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_status.isAppoint
     *
     * @mbggenerated
     */
    private Integer isappoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_status.isFinish
     *
     * @mbggenerated
     */
    private Integer isfinish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_status.applyGroup
     *
     * @mbggenerated
     */
    private String applygroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_status.appointGroup
     *
     * @mbggenerated
     */
    private Integer appointgroup;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_status.projectId
     *
     * @return the value of project_status.projectId
     *
     * @mbggenerated
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_status.projectId
     *
     * @param projectid the value for project_status.projectId
     *
     * @mbggenerated
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_status.isAppoint
     *
     * @return the value of project_status.isAppoint
     *
     * @mbggenerated
     */
    public Integer getIsappoint() {
        return isappoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_status.isAppoint
     *
     * @param isappoint the value for project_status.isAppoint
     *
     * @mbggenerated
     */
    public void setIsappoint(Integer isappoint) {
        this.isappoint = isappoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_status.isFinish
     *
     * @return the value of project_status.isFinish
     *
     * @mbggenerated
     */
    public Integer getIsfinish() {
        return isfinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_status.isFinish
     *
     * @param isfinish the value for project_status.isFinish
     *
     * @mbggenerated
     */
    public void setIsfinish(Integer isfinish) {
        this.isfinish = isfinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_status.applyGroup
     *
     * @return the value of project_status.applyGroup
     *
     * @mbggenerated
     */
    public String getApplygroup() {
        return applygroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_status.applyGroup
     *
     * @param applygroup the value for project_status.applyGroup
     *
     * @mbggenerated
     */
    public void setApplygroup(String applygroup) {
        this.applygroup = applygroup == null ? null : applygroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_status.appointGroup
     *
     * @return the value of project_status.appointGroup
     *
     * @mbggenerated
     */
    public Integer getAppointgroup() {
        return appointgroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_status.appointGroup
     *
     * @param appointgroup the value for project_status.appointGroup
     *
     * @mbggenerated
     */
    public void setAppointgroup(Integer appointgroup) {
        this.appointgroup = appointgroup;
    }
}