package com.eumenides.entity;

import java.util.Date;

public class ReEducation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_education.educationId
     *
     * @mbggenerated
     */
    private Integer educationid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_education.resumeId
     *
     * @mbggenerated
     */
    private Integer resumeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_education.school
     *
     * @mbggenerated
     */
    private String school;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_education.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_education.marjor
     *
     * @mbggenerated
     */
    private String marjor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_education.education
     *
     * @mbggenerated
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_education.startTime
     *
     * @mbggenerated
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_education.endTime
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_education.courses
     *
     * @mbggenerated
     */
    private String courses;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_education.honor
     *
     * @mbggenerated
     */
    private String honor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_education.educationId
     *
     * @return the value of re_education.educationId
     *
     * @mbggenerated
     */
    public Integer getEducationid() {
        return educationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_education.educationId
     *
     * @param educationid the value for re_education.educationId
     *
     * @mbggenerated
     */
    public void setEducationid(Integer educationid) {
        this.educationid = educationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_education.resumeId
     *
     * @return the value of re_education.resumeId
     *
     * @mbggenerated
     */
    public Integer getResumeid() {
        return resumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_education.resumeId
     *
     * @param resumeid the value for re_education.resumeId
     *
     * @mbggenerated
     */
    public void setResumeid(Integer resumeid) {
        this.resumeid = resumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_education.school
     *
     * @return the value of re_education.school
     *
     * @mbggenerated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_education.school
     *
     * @param school the value for re_education.school
     *
     * @mbggenerated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_education.city
     *
     * @return the value of re_education.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_education.city
     *
     * @param city the value for re_education.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_education.marjor
     *
     * @return the value of re_education.marjor
     *
     * @mbggenerated
     */
    public String getMarjor() {
        return marjor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_education.marjor
     *
     * @param marjor the value for re_education.marjor
     *
     * @mbggenerated
     */
    public void setMarjor(String marjor) {
        this.marjor = marjor == null ? null : marjor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_education.education
     *
     * @return the value of re_education.education
     *
     * @mbggenerated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_education.education
     *
     * @param education the value for re_education.education
     *
     * @mbggenerated
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_education.startTime
     *
     * @return the value of re_education.startTime
     *
     * @mbggenerated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_education.startTime
     *
     * @param starttime the value for re_education.startTime
     *
     * @mbggenerated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_education.endTime
     *
     * @return the value of re_education.endTime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_education.endTime
     *
     * @param endtime the value for re_education.endTime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_education.courses
     *
     * @return the value of re_education.courses
     *
     * @mbggenerated
     */
    public String getCourses() {
        return courses;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_education.courses
     *
     * @param courses the value for re_education.courses
     *
     * @mbggenerated
     */
    public void setCourses(String courses) {
        this.courses = courses == null ? null : courses.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_education.honor
     *
     * @return the value of re_education.honor
     *
     * @mbggenerated
     */
    public String getHonor() {
        return honor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_education.honor
     *
     * @param honor the value for re_education.honor
     *
     * @mbggenerated
     */
    public void setHonor(String honor) {
        this.honor = honor == null ? null : honor.trim();
    }
}