package com.eumenides.entity;

public class ReEvaluation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_evaluation.resumeId
     *
     * @mbggenerated
     */
    private Integer resumeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_evaluation.evaluation
     *
     * @mbggenerated
     */
    private String evaluation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_evaluation.resumeId
     *
     * @return the value of re_evaluation.resumeId
     *
     * @mbggenerated
     */
    public Integer getResumeid() {
        return resumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_evaluation.resumeId
     *
     * @param resumeid the value for re_evaluation.resumeId
     *
     * @mbggenerated
     */
    public void setResumeid(Integer resumeid) {
        this.resumeid = resumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_evaluation.evaluation
     *
     * @return the value of re_evaluation.evaluation
     *
     * @mbggenerated
     */
    public String getEvaluation() {
        return evaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_evaluation.evaluation
     *
     * @param evaluation the value for re_evaluation.evaluation
     *
     * @mbggenerated
     */
    public void setEvaluation(String evaluation) {
        this.evaluation = evaluation == null ? null : evaluation.trim();
    }
}