package com.eumenides.entity;

import java.util.Date;

public class ReInternship {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_internship.InternshipId
     *
     * @mbggenerated
     */
    private Integer internshipid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_internship.resumeId
     *
     * @mbggenerated
     */
    private Integer resumeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_internship.company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_internship.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_internship.startTime
     *
     * @mbggenerated
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_internship.endtime
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_internship.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_internship.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_internship.InternshipId
     *
     * @return the value of re_internship.InternshipId
     *
     * @mbggenerated
     */
    public Integer getInternshipid() {
        return internshipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_internship.InternshipId
     *
     * @param internshipid the value for re_internship.InternshipId
     *
     * @mbggenerated
     */
    public void setInternshipid(Integer internshipid) {
        this.internshipid = internshipid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_internship.resumeId
     *
     * @return the value of re_internship.resumeId
     *
     * @mbggenerated
     */
    public Integer getResumeid() {
        return resumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_internship.resumeId
     *
     * @param resumeid the value for re_internship.resumeId
     *
     * @mbggenerated
     */
    public void setResumeid(Integer resumeid) {
        this.resumeid = resumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_internship.company
     *
     * @return the value of re_internship.company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_internship.company
     *
     * @param company the value for re_internship.company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_internship.position
     *
     * @return the value of re_internship.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_internship.position
     *
     * @param position the value for re_internship.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_internship.startTime
     *
     * @return the value of re_internship.startTime
     *
     * @mbggenerated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_internship.startTime
     *
     * @param starttime the value for re_internship.startTime
     *
     * @mbggenerated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_internship.endtime
     *
     * @return the value of re_internship.endtime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_internship.endtime
     *
     * @param endtime the value for re_internship.endtime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_internship.city
     *
     * @return the value of re_internship.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_internship.city
     *
     * @param city the value for re_internship.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_internship.description
     *
     * @return the value of re_internship.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_internship.description
     *
     * @param description the value for re_internship.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}