package com.eumenides.entity;

public class RelateUserGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relate_user_group.relateId
     *
     * @mbggenerated
     */
    private Integer relateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relate_user_group.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relate_user_group.groupId
     *
     * @mbggenerated
     */
    private Integer groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relate_user_group.place
     *
     * @mbggenerated
     */
    private Integer place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relate_user_group.default_resume
     *
     * @mbggenerated
     */
    private Integer defaultResume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relate_user_group.relateId
     *
     * @return the value of relate_user_group.relateId
     *
     * @mbggenerated
     */
    public Integer getRelateid() {
        return relateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relate_user_group.relateId
     *
     * @param relateid the value for relate_user_group.relateId
     *
     * @mbggenerated
     */
    public void setRelateid(Integer relateid) {
        this.relateid = relateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relate_user_group.userId
     *
     * @return the value of relate_user_group.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relate_user_group.userId
     *
     * @param userid the value for relate_user_group.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relate_user_group.groupId
     *
     * @return the value of relate_user_group.groupId
     *
     * @mbggenerated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relate_user_group.groupId
     *
     * @param groupid the value for relate_user_group.groupId
     *
     * @mbggenerated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relate_user_group.place
     *
     * @return the value of relate_user_group.place
     *
     * @mbggenerated
     */
    public Integer getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relate_user_group.place
     *
     * @param place the value for relate_user_group.place
     *
     * @mbggenerated
     */
    public void setPlace(Integer place) {
        this.place = place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relate_user_group.default_resume
     *
     * @return the value of relate_user_group.default_resume
     *
     * @mbggenerated
     */
    public Integer getDefaultResume() {
        return defaultResume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relate_user_group.default_resume
     *
     * @param defaultResume the value for relate_user_group.default_resume
     *
     * @mbggenerated
     */
    public void setDefaultResume(Integer defaultResume) {
        this.defaultResume = defaultResume;
    }
}