package com.eumenides.entity;

public class RelateGroupProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relate_group_project.bidId
     *
     * @mbggenerated
     */
    private Integer bidid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relate_group_project.projectId
     *
     * @mbggenerated
     */
    private Integer projectid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relate_group_project.groupId
     *
     * @mbggenerated
     */
    private Integer groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column relate_group_project.isEntrusted
     *
     * @mbggenerated
     */
    private Integer isentrusted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relate_group_project.bidId
     *
     * @return the value of relate_group_project.bidId
     *
     * @mbggenerated
     */
    public Integer getBidid() {
        return bidid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relate_group_project.bidId
     *
     * @param bidid the value for relate_group_project.bidId
     *
     * @mbggenerated
     */
    public void setBidid(Integer bidid) {
        this.bidid = bidid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relate_group_project.projectId
     *
     * @return the value of relate_group_project.projectId
     *
     * @mbggenerated
     */
    public Integer getProjectid() {
        return projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relate_group_project.projectId
     *
     * @param projectid the value for relate_group_project.projectId
     *
     * @mbggenerated
     */
    public void setProjectid(Integer projectid) {
        this.projectid = projectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relate_group_project.groupId
     *
     * @return the value of relate_group_project.groupId
     *
     * @mbggenerated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relate_group_project.groupId
     *
     * @param groupid the value for relate_group_project.groupId
     *
     * @mbggenerated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column relate_group_project.isEntrusted
     *
     * @return the value of relate_group_project.isEntrusted
     *
     * @mbggenerated
     */
    public Integer getIsentrusted() {
        return isentrusted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column relate_group_project.isEntrusted
     *
     * @param isentrusted the value for relate_group_project.isEntrusted
     *
     * @mbggenerated
     */
    public void setIsentrusted(Integer isentrusted) {
        this.isentrusted = isentrusted;
    }
}