package com.eumenides.entity;

import java.util.Date;

public class ReScience {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_science.scienceId
     *
     * @mbggenerated
     */
    private Integer scienceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_science.resumeId
     *
     * @mbggenerated
     */
    private Integer resumeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_science.project
     *
     * @mbggenerated
     */
    private String project;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_science.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_science.start
     *
     * @mbggenerated
     */
    private Date start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_science.end
     *
     * @mbggenerated
     */
    private Date end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_science.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_science.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_science.scienceId
     *
     * @return the value of re_science.scienceId
     *
     * @mbggenerated
     */
    public Integer getScienceid() {
        return scienceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_science.scienceId
     *
     * @param scienceid the value for re_science.scienceId
     *
     * @mbggenerated
     */
    public void setScienceid(Integer scienceid) {
        this.scienceid = scienceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_science.resumeId
     *
     * @return the value of re_science.resumeId
     *
     * @mbggenerated
     */
    public Integer getResumeid() {
        return resumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_science.resumeId
     *
     * @param resumeid the value for re_science.resumeId
     *
     * @mbggenerated
     */
    public void setResumeid(Integer resumeid) {
        this.resumeid = resumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_science.project
     *
     * @return the value of re_science.project
     *
     * @mbggenerated
     */
    public String getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_science.project
     *
     * @param project the value for re_science.project
     *
     * @mbggenerated
     */
    public void setProject(String project) {
        this.project = project == null ? null : project.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_science.position
     *
     * @return the value of re_science.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_science.position
     *
     * @param position the value for re_science.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_science.start
     *
     * @return the value of re_science.start
     *
     * @mbggenerated
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_science.start
     *
     * @param start the value for re_science.start
     *
     * @mbggenerated
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_science.end
     *
     * @return the value of re_science.end
     *
     * @mbggenerated
     */
    public Date getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_science.end
     *
     * @param end the value for re_science.end
     *
     * @mbggenerated
     */
    public void setEnd(Date end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_science.city
     *
     * @return the value of re_science.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_science.city
     *
     * @param city the value for re_science.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_science.description
     *
     * @return the value of re_science.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_science.description
     *
     * @param description the value for re_science.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}