package com.eumenides.entity;

import java.util.Date;

public class ReSchool {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_school.school_exp_Id
     *
     * @mbggenerated
     */
    private Integer schoolExpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_school.resumeId
     *
     * @mbggenerated
     */
    private Integer resumeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_school.activity
     *
     * @mbggenerated
     */
    private String activity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_school.role
     *
     * @mbggenerated
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_school.start
     *
     * @mbggenerated
     */
    private Date start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_school.end
     *
     * @mbggenerated
     */
    private Date end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_school.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column re_school.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_school.school_exp_Id
     *
     * @return the value of re_school.school_exp_Id
     *
     * @mbggenerated
     */
    public Integer getSchoolExpId() {
        return schoolExpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_school.school_exp_Id
     *
     * @param schoolExpId the value for re_school.school_exp_Id
     *
     * @mbggenerated
     */
    public void setSchoolExpId(Integer schoolExpId) {
        this.schoolExpId = schoolExpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_school.resumeId
     *
     * @return the value of re_school.resumeId
     *
     * @mbggenerated
     */
    public Integer getResumeid() {
        return resumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_school.resumeId
     *
     * @param resumeid the value for re_school.resumeId
     *
     * @mbggenerated
     */
    public void setResumeid(Integer resumeid) {
        this.resumeid = resumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_school.activity
     *
     * @return the value of re_school.activity
     *
     * @mbggenerated
     */
    public String getActivity() {
        return activity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_school.activity
     *
     * @param activity the value for re_school.activity
     *
     * @mbggenerated
     */
    public void setActivity(String activity) {
        this.activity = activity == null ? null : activity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_school.role
     *
     * @return the value of re_school.role
     *
     * @mbggenerated
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_school.role
     *
     * @param role the value for re_school.role
     *
     * @mbggenerated
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_school.start
     *
     * @return the value of re_school.start
     *
     * @mbggenerated
     */
    public Date getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_school.start
     *
     * @param start the value for re_school.start
     *
     * @mbggenerated
     */
    public void setStart(Date start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_school.end
     *
     * @return the value of re_school.end
     *
     * @mbggenerated
     */
    public Date getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_school.end
     *
     * @param end the value for re_school.end
     *
     * @mbggenerated
     */
    public void setEnd(Date end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_school.city
     *
     * @return the value of re_school.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_school.city
     *
     * @param city the value for re_school.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column re_school.description
     *
     * @return the value of re_school.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column re_school.description
     *
     * @param description the value for re_school.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}