package com.eumenides.entity;

import java.util.Date;

public class SelectUserRecruit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_user_recruit.deliverId
     *
     * @mbggenerated
     */
    private Integer deliverid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_user_recruit.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_user_recruit.resumeId
     *
     * @mbggenerated
     */
    private Integer resumeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_user_recruit.recruitId
     *
     * @mbggenerated
     */
    private Integer recruitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_user_recruit.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column select_user_recruit.time
     *
     * @mbggenerated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_user_recruit.deliverId
     *
     * @return the value of select_user_recruit.deliverId
     *
     * @mbggenerated
     */
    public Integer getDeliverid() {
        return deliverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_user_recruit.deliverId
     *
     * @param deliverid the value for select_user_recruit.deliverId
     *
     * @mbggenerated
     */
    public void setDeliverid(Integer deliverid) {
        this.deliverid = deliverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_user_recruit.userId
     *
     * @return the value of select_user_recruit.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_user_recruit.userId
     *
     * @param userid the value for select_user_recruit.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_user_recruit.resumeId
     *
     * @return the value of select_user_recruit.resumeId
     *
     * @mbggenerated
     */
    public Integer getResumeid() {
        return resumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_user_recruit.resumeId
     *
     * @param resumeid the value for select_user_recruit.resumeId
     *
     * @mbggenerated
     */
    public void setResumeid(Integer resumeid) {
        this.resumeid = resumeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_user_recruit.recruitId
     *
     * @return the value of select_user_recruit.recruitId
     *
     * @mbggenerated
     */
    public Integer getRecruitid() {
        return recruitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_user_recruit.recruitId
     *
     * @param recruitid the value for select_user_recruit.recruitId
     *
     * @mbggenerated
     */
    public void setRecruitid(Integer recruitid) {
        this.recruitid = recruitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_user_recruit.status
     *
     * @return the value of select_user_recruit.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_user_recruit.status
     *
     * @param status the value for select_user_recruit.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column select_user_recruit.time
     *
     * @return the value of select_user_recruit.time
     *
     * @mbggenerated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column select_user_recruit.time
     *
     * @param time the value for select_user_recruit.time
     *
     * @mbggenerated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}