package com.eumenides.dao;

import com.eumenides.entity.CollectUserProject;
import com.eumenides.entity.CollectUserProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollectUserProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_project
     *
     * @mbggenerated
     */
    int countByExample(CollectUserProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_project
     *
     * @mbggenerated
     */
    int deleteByExample(CollectUserProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_project
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer collectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_project
     *
     * @mbggenerated
     */
    int insert(CollectUserProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_project
     *
     * @mbggenerated
     */
    int insertSelective(CollectUserProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_project
     *
     * @mbggenerated
     */
    List<CollectUserProject> selectByExample(CollectUserProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_project
     *
     * @mbggenerated
     */
    CollectUserProject selectByPrimaryKey(Integer collectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_project
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CollectUserProject record, @Param("example") CollectUserProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_project
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CollectUserProject record, @Param("example") CollectUserProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CollectUserProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CollectUserProject record);
}