package com.eumenides.dao;

import com.eumenides.entity.CollectUserRecruit;
import com.eumenides.entity.CollectUserRecruitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollectUserRecruitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_recruit
     *
     * @mbggenerated
     */
    int countByExample(CollectUserRecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_recruit
     *
     * @mbggenerated
     */
    int deleteByExample(CollectUserRecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_recruit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer collectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_recruit
     *
     * @mbggenerated
     */
    int insert(CollectUserRecruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_recruit
     *
     * @mbggenerated
     */
    int insertSelective(CollectUserRecruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_recruit
     *
     * @mbggenerated
     */
    List<CollectUserRecruit> selectByExample(CollectUserRecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_recruit
     *
     * @mbggenerated
     */
    CollectUserRecruit selectByPrimaryKey(Integer collectid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_recruit
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CollectUserRecruit record, @Param("example") CollectUserRecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_recruit
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CollectUserRecruit record, @Param("example") CollectUserRecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_recruit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CollectUserRecruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_user_recruit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CollectUserRecruit record);
}