package com.eumenides.dao;

import com.eumenides.entity.CoRecruit;
import com.eumenides.entity.CoRecruitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoRecruitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_recruit
     *
     * @mbggenerated
     */
    int countByExample(CoRecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_recruit
     *
     * @mbggenerated
     */
    int deleteByExample(CoRecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_recruit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer recruitid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_recruit
     *
     * @mbggenerated
     */
    int insert(CoRecruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_recruit
     *
     * @mbggenerated
     */
    int insertSelective(CoRecruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_recruit
     *
     * @mbggenerated
     */
    List<CoRecruit> selectByExample(CoRecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_recruit
     *
     * @mbggenerated
     */
    CoRecruit selectByPrimaryKey(Integer recruitid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_recruit
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CoRecruit record, @Param("example") CoRecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_recruit
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CoRecruit record, @Param("example") CoRecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_recruit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CoRecruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table co_recruit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CoRecruit record);
}