package com.eumenides.dao;

import com.eumenides.entity.NoticeParam;
import com.eumenides.entity.NoticeParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NoticeParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_param
     *
     * @mbggenerated
     */
    int countByExample(NoticeParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_param
     *
     * @mbggenerated
     */
    int deleteByExample(NoticeParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_param
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer paramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_param
     *
     * @mbggenerated
     */
    int insert(NoticeParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_param
     *
     * @mbggenerated
     */
    int insertSelective(NoticeParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_param
     *
     * @mbggenerated
     */
    List<NoticeParam> selectByExample(NoticeParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_param
     *
     * @mbggenerated
     */
    NoticeParam selectByPrimaryKey(Integer paramId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_param
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") NoticeParam record, @Param("example") NoticeParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_param
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") NoticeParam record, @Param("example") NoticeParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NoticeParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NoticeParam record);
}