package com.eumenides.dao;

import com.eumenides.entity.PersonalInf;
import com.eumenides.entity.PersonalInfExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PersonalInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_inf
     *
     * @mbggenerated
     */
    int countByExample(PersonalInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_inf
     *
     * @mbggenerated
     */
    int deleteByExample(PersonalInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_inf
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_inf
     *
     * @mbggenerated
     */
    int insert(PersonalInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_inf
     *
     * @mbggenerated
     */
    int insertSelective(PersonalInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_inf
     *
     * @mbggenerated
     */
    List<PersonalInf> selectByExample(PersonalInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_inf
     *
     * @mbggenerated
     */
    PersonalInf selectByPrimaryKey(String email);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_inf
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") PersonalInf record, @Param("example") PersonalInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_inf
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") PersonalInf record, @Param("example") PersonalInfExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_inf
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PersonalInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table personal_inf
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PersonalInf record);
}