package com.eumenides.dao;

import com.eumenides.entity.ReEducation;
import com.eumenides.entity.ReEducationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReEducationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_education
     *
     * @mbggenerated
     */
    int countByExample(ReEducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_education
     *
     * @mbggenerated
     */
    int deleteByExample(ReEducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_education
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer educationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_education
     *
     * @mbggenerated
     */
    int insert(ReEducation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_education
     *
     * @mbggenerated
     */
    int insertSelective(ReEducation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_education
     *
     * @mbggenerated
     */
    List<ReEducation> selectByExample(ReEducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_education
     *
     * @mbggenerated
     */
    ReEducation selectByPrimaryKey(Integer educationid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_education
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReEducation record, @Param("example") ReEducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_education
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReEducation record, @Param("example") ReEducationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_education
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReEducation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_education
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReEducation record);
}