package com.eumenides.dao;

import com.eumenides.entity.RelateUserGroup;
import com.eumenides.entity.RelateUserGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RelateUserGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relate_user_group
     *
     * @mbggenerated
     */
    int countByExample(RelateUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relate_user_group
     *
     * @mbggenerated
     */
    int deleteByExample(RelateUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relate_user_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer relateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relate_user_group
     *
     * @mbggenerated
     */
    int insert(RelateUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relate_user_group
     *
     * @mbggenerated
     */
    int insertSelective(RelateUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relate_user_group
     *
     * @mbggenerated
     */
    List<RelateUserGroup> selectByExample(RelateUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relate_user_group
     *
     * @mbggenerated
     */
    RelateUserGroup selectByPrimaryKey(Integer relateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relate_user_group
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RelateUserGroup record, @Param("example") RelateUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relate_user_group
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RelateUserGroup record, @Param("example") RelateUserGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relate_user_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RelateUserGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table relate_user_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RelateUserGroup record);
}