package com.eumenides.dao;

import com.eumenides.entity.ReScience;
import com.eumenides.entity.ReScienceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReScienceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_science
     *
     * @mbggenerated
     */
    int countByExample(ReScienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_science
     *
     * @mbggenerated
     */
    int deleteByExample(ReScienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_science
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer scienceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_science
     *
     * @mbggenerated
     */
    int insert(ReScience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_science
     *
     * @mbggenerated
     */
    int insertSelective(ReScience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_science
     *
     * @mbggenerated
     */
    List<ReScience> selectByExample(ReScienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_science
     *
     * @mbggenerated
     */
    ReScience selectByPrimaryKey(Integer scienceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_science
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ReScience record, @Param("example") ReScienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_science
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ReScience record, @Param("example") ReScienceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_science
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ReScience record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table re_science
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ReScience record);
}