package com.eumenides.dao;

import com.eumenides.entity.SelectUserRecruit;
import com.eumenides.entity.SelectUserRecruitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SelectUserRecruitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_user_recruit
     *
     * @mbggenerated
     */
    int countByExample(SelectUserRecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_user_recruit
     *
     * @mbggenerated
     */
    int deleteByExample(SelectUserRecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_user_recruit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer deliverid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_user_recruit
     *
     * @mbggenerated
     */
    int insert(SelectUserRecruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_user_recruit
     *
     * @mbggenerated
     */
    int insertSelective(SelectUserRecruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_user_recruit
     *
     * @mbggenerated
     */
    List<SelectUserRecruit> selectByExample(SelectUserRecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_user_recruit
     *
     * @mbggenerated
     */
    SelectUserRecruit selectByPrimaryKey(Integer deliverid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_user_recruit
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SelectUserRecruit record, @Param("example") SelectUserRecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_user_recruit
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SelectUserRecruit record, @Param("example") SelectUserRecruitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_user_recruit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SelectUserRecruit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table select_user_recruit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SelectUserRecruit record);
}