package com.eumenides.dao;

import com.eumenides.entity.UserTag;
import com.eumenides.entity.UserTagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag
     *
     * @mbggenerated
     */
    int countByExample(UserTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag
     *
     * @mbggenerated
     */
    int deleteByExample(UserTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer userTagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag
     *
     * @mbggenerated
     */
    int insert(UserTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag
     *
     * @mbggenerated
     */
    int insertSelective(UserTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag
     *
     * @mbggenerated
     */
    List<UserTag> selectByExample(UserTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag
     *
     * @mbggenerated
     */
    UserTag selectByPrimaryKey(Integer userTagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserTag record, @Param("example") UserTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserTag record, @Param("example") UserTagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserTag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_tag
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserTag record);
}